import intf_libs += libssl%lib{ssl}
import intf_libs += libcrypto%lib{crypto}
import intf_libs += libcrails-logger%lib{crails-logger}
import intf_libs += libcrails-readfile%lib{crails-readfile}

lib{crails-ssh}: {hxx ixx txx cxx}{**} $impl_libs $intf_libs

hxx{export}@./: cxx.importable = false

# Build options.
#
cxx.poptions =+ "-I$out_root" "-I$src_root"

{hbmia obja}{*}: cxx.poptions += -DLIBCRAILS_STATIC_BUILD
{hbmis objs}{*}: cxx.poptions += -DLIBCRAILS_SHARED_BUILD

# Export options.
#
lib{crails-ssh}:
{
  cxx.export.poptions = "-I$out_root/libcrails-ssh/" "-I$src_root/libcrails-ssh/"
  cxx.export.libs = $intf_libs
}

liba{crails-ssh}: cxx.export.poptions += -DLIBCRAILS_STATIC
libs{crails-ssh}: cxx.export.poptions += -DLIBCRAILS_SHARED

if $version.pre_release
  lib{crails-ssh}: bin.lib.version = "-$version.project_id"
else
  lib{crails-ssh}: bin.lib.version = "-$version.major.$version.minor"

{hxx ixx txx}{*}:
{
  install         = include/
  install.subdirs = true
}
